name: Main Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.10"

jobs:

  lint:
    uses: ./.github/workflows/lint.yaml
    with: 
      ENFORCE_BLACK: true
      ENFORCE_PYRIGHT: true
      ENFORCE_BANDIT: false
      ENFORCE_FLAKE8: false
