name: Main Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    uses: ./.github/workflows/lint.yaml
    with: 
      ENFORCE_BLACK: "true"
      ENFORCE_PYRIGHT: "true"
      ENFORCE_BANDIT: "false"
      ENFORCE_FLAKE8: "false"
