name: Main Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.10"
  ENFORCE_BLACK: true
  ENFORCE_PYRIGHT: true
  ENFORCE_BANDIT: false
  ENFORCE_FLAKE8: false

jobs:

  lint:
    uses: .github/workflows/lint.yaml
